name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: install dependencies
      run: |
        npm install

    - name: check lint errors
      run: |
        npm run prepublishOnly
        npm run pretest
        npm run precommit

    - name: run tests
      run: |
        npm run test

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true

    - name: generate project
      run: |
        npm install -g yo
        npm link
        mkdir app
        yo jekyll-starter-kit
